# Generated by Django 5.0.1 on 2024-03-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='borrowers',
        ),
        migrations.AddField(
            model_name='course',
            name='taken_by',
            field=models.ManyToManyField(blank=True, related_name='enrolled_course', to='teachers.useraccount'),
        ),
    ]
