# Generated by Django 5.0.1 on 2024-03-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_taken_by_alter_course_author'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Course',
            new_name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='taken_by',
            field=models.ManyToManyField(blank=True, related_name='enrolled_course', to='teachers.useraccount'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='teachers.useraccount'),
        ),
    ]
